name: ospy_docs
dependencies:
  - python=3.8
  - pandoc
  - sphinx
  - pip
  - pip:
    - xarray
    - intake
    - intake-xarray
    - ipython
    - numpydoc
    - sphinx_rtd_theme
    - nbsphinx
    - xgcm
    - aiohttp
